services:
  - type: web
    name: ecommerce-backend
    plan: free
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        value: dpg-d7el1r57vvec7381a12g-a
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: ecommerce_id37
      - key: DB_USER
        value: ecommerce_user
      - key: DB_PASSWORD
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://ecommerce-frontend.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_MS
        value: 3600000
    healthCheckPath: /actuator/health

  - type: web
    name: ecommerce-frontend
    plan: free
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_API_BASE_URL
        value: https://ecommerce-backend.onrender.com/api
      - key: PORT
        value: 80

  - type: web
    name: ecommerce-dashboard
    plan: free
    runtime: docker
    dockerfilePath: ./dashboard/Dockerfile
    dockerContext: ./dashboard
    envVars:
      - key: VITE_API_BASE_URL
        value: https://ecommerce-backend.onrender.com/api
      - key: PORT
        value: 80